/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as VideoConsultationRouteImport } from './routes/video-consultation'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as EquipmentIndexRouteImport } from './routes/equipment.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as TherapistDashboardRouteImport } from './routes/therapist.dashboard'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as ApiPublicProxySplatRouteImport } from './routes/api/public/proxy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoConsultationRoute = VideoConsultationRouteImport.update({
  id: '/video-consultation',
  path: '/video-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentIndexRoute = EquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistDashboardRoute = TherapistDashboardRouteImport.update({
  id: '/therapist/dashboard',
  path: '/therapist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxySplatRoute = ApiPublicProxySplatRouteImport.update({
  id: '/api/public/proxy/$',
  path: '/api/public/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/therapists': typeof TherapistsRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/videos': typeof VideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/therapists': typeof TherapistsRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/videos': typeof VideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/blogs': typeof BlogsIndexRoute
  '/careers': typeof CareersIndexRoute
  '/equipment': typeof EquipmentIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/therapists': typeof TherapistsRoute
  '/video-consultation': typeof VideoConsultationRoute
  '/videos': typeof VideosRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/therapist/dashboard': typeof TherapistDashboardRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/blogs/': typeof BlogsIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/equipment/': typeof EquipmentIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/public/proxy/$': typeof ApiPublicProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/therapists'
    | '/video-consultation'
    | '/videos'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/therapist/dashboard'
    | '/user/dashboard'
    | '/blogs/'
    | '/careers/'
    | '/equipment/'
    | '/services/'
    | '/api/public/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/therapists'
    | '/video-consultation'
    | '/videos'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/therapist/dashboard'
    | '/user/dashboard'
    | '/blogs'
    | '/careers'
    | '/equipment'
    | '/services'
    | '/api/public/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/testimonials'
    | '/therapists'
    | '/video-consultation'
    | '/videos'
    | '/blogs/$slug'
    | '/careers/$slug'
    | '/services/$slug'
    | '/therapist/dashboard'
    | '/user/dashboard'
    | '/blogs/'
    | '/careers/'
    | '/equipment/'
    | '/services/'
    | '/api/public/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TherapistsRoute: typeof TherapistsRoute
  VideoConsultationRoute: typeof VideoConsultationRoute
  VideosRoute: typeof VideosRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TherapistDashboardRoute: typeof TherapistDashboardRoute
  UserDashboardRoute: typeof UserDashboardRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  EquipmentIndexRoute: typeof EquipmentIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicProxySplatRoute: typeof ApiPublicProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-consultation': {
      id: '/video-consultation'
      path: '/video-consultation'
      fullPath: '/video-consultation'
      preLoaderRoute: typeof VideoConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/': {
      id: '/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof EquipmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist/dashboard': {
      id: '/therapist/dashboard'
      path: '/therapist/dashboard'
      fullPath: '/therapist/dashboard'
      preLoaderRoute: typeof TherapistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/$': {
      id: '/api/public/proxy/$'
      path: '/api/public/proxy/$'
      fullPath: '/api/public/proxy/$'
      preLoaderRoute: typeof ApiPublicProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TherapistsRoute: TherapistsRoute,
  VideoConsultationRoute: VideoConsultationRoute,
  VideosRoute: VideosRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  CareersSlugRoute: CareersSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TherapistDashboardRoute: TherapistDashboardRoute,
  UserDashboardRoute: UserDashboardRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  EquipmentIndexRoute: EquipmentIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicProxySplatRoute: ApiPublicProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
